### ISSUE TITLE
add dataset_curation section to yaml file

### ISSUE THREAD

**Issue by roblanf** [roblanf/PartitionedAlignments#56]
this section should be used to describe exactly what a user would need to do to get from the original dryad link to the dataset in our database.

For exmaple:

* which alignment file to download
* origin of partitioning information
* justification for that alignment file over others (e.g. this is the alignment used to create figure 1 in the paper)
* any edits made to that alignment file (e.g. changing characters in names etc. - this can point to a script in the repo which does this)
* any sequences removed

So, we can have a section like this

```
dataset:
    DOI: dx.doi.org/10.5524/101041
    license: CC0
    used for tree inference: yes
    dataset_curation:
        alignment_file: 
        partition_information:
        justification:
        name_edits:
        sequence_edits:
```
